# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'V-Manager' do

pod 'AFNetworking'
pod 'CocoaLumberjack'
pod 'ReactiveObjC'
pod 'SDWebImage', "~> 3.8.2"
pod 'SVProgressHUD'
pod 'MBProgressHUD'
pod 'Toast'
pod 'MJRefresh'
pod 'Masonry'
pod 'WMPageController'

end
